### ISSUE TITLE
Swift version doesn't compile in Xcode 6 final

### ISSUE THREAD

**Issue by altruic** [ivoleko/ILTranslucentView#10]
The Swift version of this class doesn't compile in the final Xcode 6 release. I adjusted the code so that Xcode stopped complaining about errors and warnings in the IDE, but the compile still failed with:
```
Referring to an argument in another function!
  store float %1, float* %.coerced, !dbg !390
LLVM ERROR: Broken function found, compilation aborted!
```
This error went away when I commented out `bounds` *and* `backgroundColor`, but I didn't find anything obviously wrong with those methods. Changing the type of `backgroundColor` to `UIColor?` (like the base class) didn't resolve the compiler error, either.

Any ideas on what the problem might be? I'm pretty new to Swift errors. Thanks.

**Comment by ivoleko** [comment]
This is fixed now.
