### ISSUE TITLE
No Blurr

### ISSUE THREAD

**Issue by rajohns08** [ivoleko/ILTranslucentView#11]
There doesn't seem to be any blurr effect for me. just a transparent view. I have tried setting translucent property to YES and NO.

**Comment by Urkman** [comment]
I have the same problem :(
Any solution for this?

**Comment by pangelovski** [comment]
Had similiar issue. If you are using storyboards, make sure that you have set the alpha to 1 and background color to clear color in the interface builder for that view.

**Comment by ivoleko** [comment]
We do not have such problems in new versions.
